steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/warm-helix-345714/first_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/warm-helix-345714/first_app']